# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: colink_remote_storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63olink_remote_storage.proto\x12\x15\x63olink_remote_storage\"K\n\x0c\x43reateParams\x12\x17\n\x0fremote_key_name\x18\x01 \x01(\t\x12\x11\n\tis_public\x18\x02 \x01(\x08\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"K\n\nReadParams\x12\x17\n\x0fremote_key_name\x18\x01 \x01(\t\x12\x11\n\tis_public\x18\x02 \x01(\x08\x12\x11\n\tholder_id\x18\x03 \x01(\t\"K\n\x0cUpdateParams\x12\x17\n\x0fremote_key_name\x18\x01 \x01(\t\x12\x11\n\tis_public\x18\x02 \x01(\x08\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\":\n\x0c\x44\x65leteParams\x12\x17\n\x0fremote_key_name\x18\x01 \x01(\t\x12\x11\n\tis_public\x18\x02 \x01(\x08\x62\x06proto3')



_CREATEPARAMS = DESCRIPTOR.message_types_by_name['CreateParams']
_READPARAMS = DESCRIPTOR.message_types_by_name['ReadParams']
_UPDATEPARAMS = DESCRIPTOR.message_types_by_name['UpdateParams']
_DELETEPARAMS = DESCRIPTOR.message_types_by_name['DeleteParams']
CreateParams = _reflection.GeneratedProtocolMessageType('CreateParams', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPARAMS,
  '__module__' : 'colink_remote_storage_pb2'
  # @@protoc_insertion_point(class_scope:colink_remote_storage.CreateParams)
  })
_sym_db.RegisterMessage(CreateParams)

ReadParams = _reflection.GeneratedProtocolMessageType('ReadParams', (_message.Message,), {
  'DESCRIPTOR' : _READPARAMS,
  '__module__' : 'colink_remote_storage_pb2'
  # @@protoc_insertion_point(class_scope:colink_remote_storage.ReadParams)
  })
_sym_db.RegisterMessage(ReadParams)

UpdateParams = _reflection.GeneratedProtocolMessageType('UpdateParams', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPARAMS,
  '__module__' : 'colink_remote_storage_pb2'
  # @@protoc_insertion_point(class_scope:colink_remote_storage.UpdateParams)
  })
_sym_db.RegisterMessage(UpdateParams)

DeleteParams = _reflection.GeneratedProtocolMessageType('DeleteParams', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPARAMS,
  '__module__' : 'colink_remote_storage_pb2'
  # @@protoc_insertion_point(class_scope:colink_remote_storage.DeleteParams)
  })
_sym_db.RegisterMessage(DeleteParams)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEPARAMS._serialized_start=54
  _CREATEPARAMS._serialized_end=129
  _READPARAMS._serialized_start=131
  _READPARAMS._serialized_end=206
  _UPDATEPARAMS._serialized_start=208
  _UPDATEPARAMS._serialized_end=283
  _DELETEPARAMS._serialized_start=285
  _DELETEPARAMS._serialized_end=343
# @@protoc_insertion_point(module_scope)
