name: colink_python_check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  colink_python_check:
    runs-on:  ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        mq: [standalone, rabbitmq, redis]
        include:
          - mq: rabbitmq
            docker_image: "rabbitmq:3.8-management"
            mq_uri: "amqp://guest:guest@localhost"
            mq_api: "http://guest:guest@localhost:15672/api"
          - mq: redis
            docker_image: "redis"
            mq_uri: "redis://localhost:16379"    
    services:
      mq:
        image: ${{ matrix.docker_image }}
        ports:
          - 5672:5672   # rabbitmq
          - 15672:15672 # rabbitmq
          - 16379:6379  # redis
      redis:  # for storage macro
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download Server
        run: bash download-server.sh
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install Requirements
        run: pip install  .
      - name: Install Pytest
        run: pip install pytest
      - name: Run tests
        if: ${{ matrix.mq != 'standalone' }}
        env:
          COLINK_SERVER_MQ_URI: ${{ matrix.mq_uri }}
          COLINK_SERVER_MQ_API: ${{ matrix.mq_api }}
        run: pytest test
      - name: Run tests (standalone)
        if: ${{ matrix.mq == 'standalone' }}
        run: pytest test
        timeout-minutes: 5
