name: colink_python_check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  colink_python_check:
    strategy:
      matrix:
        mq: [standalone, redis]
        ci_image: [ubuntu-latest, macos-latest]
        include:
          - mq: redis
            docker_image: "redis"
            mq_uri: "redis://127.0.0.1:16379"  
    runs-on: ${{ matrix.ci_image }}
    defaults:
      run:
        shell: bash  
    steps:
      - name: Install docker
        if: ${{ startsWith(matrix.ci_image, 'macos') }}
        run: |
          brew install docker
          colima start
      - name: Start container (mq)
        if: ${{ matrix.mq != 'standalone' }}
        run: docker run -d -p 5672:5672 -p 15672:15672 -p 16379:6379 ${{ matrix.docker_image }}
      - name: Start container (redis) # for storage macro
        run: docker run -d -p 6379:6379 redis
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download Server
        run: bash download-server.sh
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install Requirements
        run: pip install  .
      - name: Install Pytest
        run: pip install pytest
      - name: Install Pytest-timeout
        run: pip install pytest-timeout
      - name: Sleep
        if: ${{ matrix.mq == 'rabbitmq' }}
        run: sleep 60
      - name: Run tests (standalone)31
        if: ${{ matrix.mq == 'standalone' }}
        run: pytest test/test_user_management.py
        timeout-minutes: 2
      - name: Run tests (standalone)0
        if: ${{ matrix.mq == 'standalone' }}
        run: python3 test/test_protocol_variable_transfer_log.py
        timeout-minutes: 2
